### ISSUE TITLE
Daily Nebraskan 

### ISSUE THREAD

**Issue by jduss4** [CDRH/nebnews#35]
The Hesperian was really early to the party in 1772.  It is as surprising as the news we got on that tour of Ferguson House which said George Washington had been in the dining room of a house built in 1909.  Need to purge batch, cry, change info, reload batch.

**Comment by jduss4** [comment]
@techgique is this something that was corrected in your last neb news codesprint?

**Comment by techgique** [comment]
Yup!

Fixed back in the day after running the scripts here: https://github.com/open-oni/open-oni-scripts/tree/master/nebraska

Related blog post: https://cdrhdev.unl.edu/log/2017/repairing-nebraska-newspapers-space-time-continuum/
