### ISSUE TITLE
Missing pages of issue

### ISSUE THREAD

**Issue by jduss4** [CDRH/nebnews#42]
nbu_eisley is missing several pages from following issue:

/batches/nbu_eisley/batch_nbu_eisley_ver01/data/2010270501/00237285074/1904040802

Example:
http://nebnewspapers.unl.edu/lccn/2010270501/1904-04-08/ed-2/seq-23/

**Comment by karindalziel** [comment]
issue for this here https://github.com/CDRH/open-oni_nebraska_theme/issues/32
