### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by lweakly** [CDRH/nebnews#43]
I notice that the citation information on the bottom of NebNewspapers is:
The Plattsmouth Journal [microform]. (Plattsmouth, Neb.), 20 Aug. 1936. Chronicling America: Historic American Newspapers. Lib. of Congress. http://nebnewspapers.unl.edu/lccn/sn95069723/1936-08-20/ed-1/seq-1/

Insead of "Chronicling America: Historic American Newspapers. Lib. of Congress." I think it should be something like "Nebraska Newspapers. University of Nebraska-Lincoln Libraries" or "Nebraska Newspapers. Center for Digital Research in the Humanities, University of Nebraska-Lincoln"

**Comment by jduss4** [comment]
Fixed!  https://github.com/CDRH/nebnews/commit/01899e55209666e633ff552513f54ab54320f1b4
