### ISSUE TITLE
Plattsmouth Date Error

### ISSUE THREAD

**Issue by jduss4** [CDRH/nebnews#44]
> A search for “Milford Bates” yields one result in the period 1821 – 1834. The page in question is for June 5, 1922 and it has been incorrectly catalogued as June 5, 1822. Colonel Milford A Bates was born 1842.

@lweakly knows more about this issue

**Comment by techgique** [comment]
Fixed back in the day after running the scripts here: https://github.com/open-oni/open-oni-scripts/commit/47e47944431e481617ad9144222b62ef9c860859

Related blog post: https://cdrhdev.unl.edu/log/2017/repairing-nebraska-newspapers-space-time-continuum/
