### ISSUE TITLE
Necessary to Move To Open ONI

### ISSUE THREAD

**Issue by jduss4** [CDRH/nebnews#46]
Essentials:
- ~ability to change "chronicling america" throughout the site~
- ~overrideable theme (our theme will need to be adjusted to fit openoni base)~
- ~easy adding of new pages (Publishing History page)~
- pull from actual cities to populate search dropdown rather than hardcoded
- ensure that filtering search results by language, city, and frequency exist (I am pretty sure I had to add at least one of those)
- look at production docker deployment advice / warnings / etc

Would Need to Match Current Site
- ~customizeable "featured" pages~
- map (preferably not hard coded, which would involve writing a script which georeferenced places on ingest and then added lat / long to the db ?)

Things that We Will Need At Some Point
- essay ingest, because I don't want to copy paste more in the DB

**Comment by jduss4** [comment]
Jeremy at oregon added functionality to the map plugin which will generate the JSON from lat / lng in the database, so therefore we would only need to populate that portion.  Will populate if you have key to specific web service to geolocate

**Comment by karindalziel** [comment]
moved to https://github.com/CDRH/open-oni_nebraska_theme/issues/36
