### ISSUE TITLE
search results jquery

### ISSUE THREAD

**Issue by jduss4** [CDRH/nebnews#47]
From Mike Beccaria:
"
mbeccaria [9:33 PM] 
fyi i'm not involved with the github project but wanted to send a bug fix so someone can incorporate it . I added "jQuery.ajaxSettings.traditional = true;" to the bottom of the jquery file to fix a bug where after an advanced search with a small set of selected newspapers the search results would broaden when sorted by title or date or relevance. This is broken in chronam and the nebraska site. This was due to %5b%5D ( "[]" ) being added to the urls after the lccn variables when a sort was done.

As per this post (https://forum.jquery.com/topic/jquery-post-1-4-1-is-appending-to-vars-when-posting-from-array-within-array) I made the changes to the jquery file and the brackets disappeared and the sorting worked properly. Thought I would let you all know. Not sure if this might break something else or if there is a cleaner way to handle this, but it's what worked.
hope that helps!"

**Comment by karindalziel** [comment]
Moved to open-oni https://github.com/open-oni/open-oni/issues/336
