### ISSUE TITLE
Hesperian Student 1844 Date

### ISSUE THREAD

**Issue by jduss4** [CDRH/nebnews#50]
The Hesperian Student has a date listed as 1844, which should really be 1884.

@lweakly recommends simply removing this page entirely, as it is a cover page which doesn't appear on the other Hesperian Student issues.

When altering the batch, we should make sure that we also track down any backups / duplicates and remove it from those, also

**Comment by karindalziel** [comment]
Moved here: https://github.com/CDRH/open-oni_nebraska_theme/issues/35
