### ISSUE TITLE
"similar issues for date" problem with Pokrok Zapadu and Omaha Daily Bee

### ISSUE THREAD

**Issue by jnlsmns** [CDRH/nebnews#52]
For dates on which issues of both the Omaha Daily Bee and Pokrok Zapadu are published, "similar issues for date" are displaying at the bottom of the page, when viewing individual page images. For example, when viewing the Bee of 4 December 1912, links to every page of the Pokrok Zapadu issue for that same date are listed at the bottom of the page under the head "similar issues for date," and vice versa. Other titles appeared on this date (Daily Nebraskan & Wilberske listy), but neither of these titles appear to be linked to the Bee and Pokrok Zapadu in this way.

Links to "similar issues for date" don't display elsewhere in Nebraska Newspapers, from what I can tell, and I'm not sure why it's happening here. Once we figure out what is going on, perhaps disabling/hiding that feature for these two titles is the way to go.

http://nebnewspapers.unl.edu/lccn/sn99021999/1912-12-04/ed-1/seq-1/
http://nebnewspapers.unl.edu/lccn/sn83045348/1912-12-04/ed-1/seq-1/

**Comment by karindalziel** [comment]
Issue migrated to https://github.com/CDRH/open-oni_nebraska_theme/issues/31
